# Generated by Django 3.2.25 on 2025-01-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='bHabitat',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bird',
            name='bMigrationPattern',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='bird',
            name='bScientificName',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
