# Generated by Django 3.2.25 on 2025-01-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0003_auto_20250105_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='bimg',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
