# Generated by Django 3.2.25 on 2025-01-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0004_bird_bimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='bimg',
        ),
    ]
