# Generated by Django 3.2.25 on 2025-01-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0005_remove_bird_bimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='bimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
