# Generated by Django 3.2.25 on 2025-01-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('afood', models.CharField(blank=True, max_length=100, null=True)),
                ('ahabitat', models.CharField(blank=True, max_length=100, null=True)),
                ('acolor', models.CharField(blank=True, max_length=100, null=True)),
                ('aspecial_abilities', models.CharField(blank=True, max_length=200, null=True)),
                ('aimage', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
