# Generated by Django 3.2.25 on 2025-03-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='aimage',
            field=models.ImageField(blank=True, default='images/all animalsss.jpg', null=True, upload_to='images/'),
        ),
    ]
